# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: javadanny
  email_provider_password: 97YU5eDO5nY#
  domain_name: example.com
  mailchimp_api_key: nothing
  mailchimp_list_id: nothing
  owner_email: nothing
  secret_key_base: a6f32ccc26ef58ec348285e4c67562ca551d38531d6bb35594ecb05d2bca712796e2504dcda8466fd68a7c54bbcbcec884937bc5dca7ee024fd573c0050a0115

test:
  secret_key_base: e85f9ae1e0debd05aa2fa5b028c2c898c15ad4bddc8a31830ccebe6f26e15f29ef768d4c393c47ab9ac0f160a01312c2000de74831b14aa1b7e21373913beb71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: nothing
  email_provider_password: nothing
  domain_name: example.com
  mailchimp_api_key: nothing
  mailchimp_list_id: nothing
  owner_email: nothing
  secret_key_base: nothing
